In [15]:
import numpy as np

In [16]:
lst = [1,2,3,4]
arr = np.array(lst)

In [17]:
print(arr)

[1 2 3 4]


In [18]:
type(arr)

numpy.ndarray

In [19]:
arr

array([1, 2, 3, 4])

In [20]:
list1 = [1,2,3,4,5,7,0]
list2 = [5,6,7,8,9,0,0]
list3 = [0,1,2,3,4,5,5]

arr1 = np.array([list1,list2,list3])

In [21]:
print(arr1)

[[1 2 3 4 5 7 0]
 [5 6 7 8 9 0 0]
 [0 1 2 3 4 5 5]]


In [22]:
arr1.shape

(3, 7)

In [23]:
arr[0]

1

In [24]:
arr[3]

4

In [25]:
firstarray = [0,1,2,3,4,5]

In [26]:
#indexing
firstarray[1:]

[1, 2, 3, 4, 5]

In [27]:
firstarray[-1]

5

In [28]:
firstarray[:-2]

[0, 1, 2, 3]

In [29]:
import numpy as np
list1 = [1,2,3,4,5,7,0]
list2 = [5,6,7,8,9,0,0]
list3 = [0,1,2,3,4,5,5]

array = np.array([list1,list2,list3])

In [30]:
array

array([[1, 2, 3, 4, 5, 7, 0],
       [5, 6, 7, 8, 9, 0, 0],
       [0, 1, 2, 3, 4, 5, 5]])

In [32]:
array[1:,1:3]

array([[6, 7],
       [1, 2]])

In [11]:
array[1,3:6]

array([8, 9, 0])

In [13]:
array[0:,-1].shape

(3,)

In [33]:
array[:,0::6]

array([[1, 0],
       [5, 0],
       [0, 5]])

In [34]:
array

array([[1, 2, 3, 4, 5, 7, 0],
       [5, 6, 7, 8, 9, 0, 0],
       [0, 1, 2, 3, 4, 5, 5]])

In [35]:
array<2

array([[ True, False, False, False, False, False,  True],
       [False, False, False, False, False,  True,  True],
       [ True,  True, False, False, False, False, False]])

In [36]:
array<5

array([[ True,  True,  True,  True, False, False,  True],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True, False, False]])

In [37]:
array[array<5]

array([1, 2, 3, 4, 0, 0, 0, 0, 1, 2, 3, 4])

In [38]:
array.shape

(3, 7)

In [39]:
array.reshape(3,5)

ValueError: cannot reshape array of size 21 into shape (3,5)

In [40]:
array.reshape(7,3)

array([[1, 2, 3],
       [4, 5, 7],
       [0, 5, 6],
       [7, 8, 9],
       [0, 0, 0],
       [1, 2, 3],
       [4, 5, 5]])

In [47]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [48]:
array

array([[1, 2, 3, 4, 5, 7, 0],
       [5, 6, 7, 8, 9, 0, 0],
       [0, 1, 2, 3, 4, 5, 5]])

In [49]:
array*array

array([[ 1,  4,  9, 16, 25, 49,  0],
       [25, 36, 49, 64, 81,  0,  0],
       [ 0,  1,  4,  9, 16, 25, 25]])

In [51]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
np.random.randint(10,50,10).reshape(2,5)

array([[48, 25, 45, 26, 25],
       [33, 23, 21, 38, 17]])