In [22]:
import numpy as np

In [23]:
lst = [1,2,3,4]
arr = np.array(lst)

In [24]:
print(arr)

[1 2 3 4]


In [25]:
type(arr)

numpy.ndarray

In [26]:
arr

array([1, 2, 3, 4])

In [27]:
list1 = [1,2,3,4,5,7,0]
list2 = [5,6,7,8,9,0,0]
list3 = [0,1,2,3,4,5,5]

arr1 = np.array([list1,list2,list3])

In [28]:
print(arr1)

[[1 2 3 4 5 7 0]
 [5 6 7 8 9 0 0]
 [0 1 2 3 4 5 5]]


In [29]:
arr1.shape

(3, 7)

In [30]:
arr[0]

1

In [31]:
arr[3]

4